#server.port: 8185
spring:
#    datasource:
#        url: jdbc:postgresql://localhost:5432/testchallenge
#        username: <your_postgre_username>
#        password: <your_postgre_password>

#    datasource:
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://<your_mysql_host_or_ip>/testchallenge
#        username: <your_mysql_username>
#        password: <your_mysql_password>
#
#    jpa:
#        hibernate:
#            dialect: org.hibernate.dialect.MySQLInnoDBDialect

    datasource:
        url: jdbc:h2:mem:testchallenge
        driverClassName: org.h2.Driver
        username: sa
        password: test
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect